export const items = [
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وجبة فطار",
    price: "50 جنية",
    img: "dish2.webp",
    catagory: "فطار",
  },
  {
    id: Math.random(),
    title: "وجبة غداء",
    description: "وجبة غداء",
    price: "80 جنية",
    img: "dish1.jpg",
    catagory: "غداء",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء",
    description: "وجبة عشاء",
    price: "100 جنية",
    img: "dish3.jpg",
    catagory: "عشاء",
  },
  {
    id: Math.random(),
    title: "وجبة غداء",
    description: "وجبة غداء",
    price: "120 جنية",
    img: "dish4.jpg",
    catagory: "غداء",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء",
    description: "وجبة عشاء",
    price: "150 جنية",
    img: "dish5.jpg",
    catagory: "عشاء",
  },
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وجبة فطار",
    price: "30 جنية",
    img: "dish6.jfif",
    catagory: "فطار",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء",
    description: "وجبة عشاء",
    price: "180 جنية",
    img: "dish7.jfif",
    catagory: "عشاء",
  },
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وجبة فطار",
    price: "40 جنية",
    img: "dish9.jfif",
    catagory: "فطار",
  },
  {
    id: Math.random(),
    title: "وجبة غداء",
    description: "وجبة غداء",
    price: "155 جنية",
    img: "dish8.jfif",
    catagory: "غداء",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء",
    description: "وجبة عشاء",
    price: "190 جنية",
    img: "dish11.jfif",
    catagory: "عشاء",
  },
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وجبة فطار",
    price: "55 جنية",
    img: "dish12.jfif",
    catagory: "فطار",
  },
  {
    id: Math.random(),
    title: "وجبة غداء",
    description: "وجبة غداء",
    price: "110 جنية",
    img: "dish10.jfif",
    catagory: "غداء",
  },
];
